// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYKHkjCsOJeukdfB-UxJLV0biKge2JNB0',
    appId: '1:198540797936:web:d8befeaa87023abb311f35',
    messagingSenderId: '198540797936',
    projectId: 'samaterrain-2da58',
    authDomain: 'samaterrain-2da58.firebaseapp.com',
    storageBucket: 'samaterrain-2da58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYlJpgsGE6inFNDJYcTfXnQRuB-VZ5z7Y',
    appId: '1:198540797936:android:1c2b377690acecda311f35',
    messagingSenderId: '198540797936',
    projectId: 'samaterrain-2da58',
    storageBucket: 'samaterrain-2da58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49uc2ALPSJEBqwpSgIjzyeT0ta5fv7rA',
    appId: '1:198540797936:ios:82f7299f974acb3a311f35',
    messagingSenderId: '198540797936',
    projectId: 'samaterrain-2da58',
    storageBucket: 'samaterrain-2da58.firebasestorage.app',
    iosBundleId: 'com.example.myTerrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49uc2ALPSJEBqwpSgIjzyeT0ta5fv7rA',
    appId: '1:198540797936:ios:82f7299f974acb3a311f35',
    messagingSenderId: '198540797936',
    projectId: 'samaterrain-2da58',
    storageBucket: 'samaterrain-2da58.firebasestorage.app',
    iosBundleId: 'com.example.myTerrain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYKHkjCsOJeukdfB-UxJLV0biKge2JNB0',
    appId: '1:198540797936:web:db4a66d0a79ad775311f35',
    messagingSenderId: '198540797936',
    projectId: 'samaterrain-2da58',
    authDomain: 'samaterrain-2da58.firebaseapp.com',
    storageBucket: 'samaterrain-2da58.firebasestorage.app',
  );
}
